version: '3.3'

services:
  database:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=safexuser
      - POSTGRES_PASSWORD=safexuser
      - POSTGRES_DB=SAFEX
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
