version: '3.3'

services:
  cassandra:
    image: cassandra:3.11.5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
    restart: always
    volumes:
      - ./cassandra_data:/var/lib/cassandra
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"

