version: '3.3'

services:
  kafka-cluster:
    container_name: kafka_cluster
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181           # Zookeeper
      - 3030:3030           # Landoop UI
      - 8081-8083:8081-8083 # Rest Proxy, Schema Registry and Kafka connect
      - 9581-9585:9581-9585 # JMX Ports
      - 9092:9092           # Kafka
